server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/glsdb}
    username: ${SPRING_DATASOURCE_USERNAME:gls}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update

app:
  jwt:
    secret: ${JWT_SECRET:uma-chave-bem-grande-e-aleatoria-com-pelo-menos-32-caracteres}

